### ISSUE TITLE
FightMode.Enemy?

### ISSUE THREAD

**Issue by GriffonSpade** [ServUO/ServUO#1872]
What is the purpose of FightMode.Enemy? Currently it appears to largely be identical to FightMode.Closest (BaseCreature.GetFightModeRanking uses 'default', which is the same that Closest uses). The only current difference appears to be that it does not work at all with AcquireOnMovement in BaseCreature.OnMovement.
Is it just a dummy or stub for future use? Is there some difference outside of BaseAI.cs and BaseCreature.cs?
Also, the reference to it in BaseAI.AcquireFocusMob seems redundant, should that be removed?

**Comment by kevin-10** [comment]
It's used for myrmidex/eodon tribe.  Basically, it's giving you the option of overriding IsEnemy in the creatures particular script to limit who they attack.

**Comment by GriffonSpade** [comment]
This is already doable with the current three existing aggressive fightmodes, isn't it? (Closest, Strongest, Weakest). In fact, it's already done in the Savage and Orc mobiles. Probably Ophidian, Terathan, and Juka as well.

Either way, that would indeed make the check in BaseAI.cs redundant.
