### ISSUE TITLE
Castle Courtyard doesnt allow to lockdown\secure objects

### ISSUE THREAD

**Issue by Crome696** [ServUO/ServUO#1873]
On EA castle courtyard allows to lockdown or secure items. 

Reproduce :

- Go onto a courtyard locaton of your castle.
- Drop Item
- Say I wish to secure this

**Comment by kevin-10** [comment]
The issues and bugs are easier tracked in the servuo forums.

**Comment by kevin-10** [comment]
Actually, this was fixed a few weeks ago.
