### ISSUE TITLE
[COMBAT] Mysticism Spells QA

### ISSUE THREAD

**Issue by qbradq** [ServUO/ServUO#189]
The current implementation of Mysticism spells does not match OSI. Specific issues are:
- Evaluating Intelligence and Inscription are always considered for spell damage
- Focus and Imbuing are never considered for spell damage
- The formula for resisting a Mysticism spell currently does not consider the caster's Focus/Imbuing level
- The Enchant spell does not have the Spell Channeling and Faster Casting -1 effects when Mysticism and Focus/Imbuing >= 80.0
- The Purge Magic spell does not make consideration for allowing the immediate purging of, for example, Bless after Strength was purged
- The Sleep spell resist mechanics are not accurate
- The Sleep spell does not appear to lower attack and spell casting speed
- The Spell Trigger implementation does not check the character's Mysticism and Focus/Imbuing levels to determine the maximum circle of Mysticism spell that can be stored.
- The Spell Stone item does not have a five-minute cooldown
- The Cleansing Winds spell does not calculate reduction in healing properly for poisons cured and curses lifted
- The Spell Plague spell specifies a 1.5 second minimum delay between activations, it should be 1 second
- The Rising Colossus spell is allowed to be cast within player housing

**Comment by dmurphy22** [comment]
Thank you, this has been added to the schedule for publish 55.
