### ISSUE TITLE
Code duplicates

### ISSUE THREAD

**Issue by jdphenix** [ServUO/ServUO#1914]
There's a lot of duplicated code in the ServUO code base. That's fine, I have pruning ~~shears~~ fingers. 

Here's a report of it. Some of this is probably not worth going after, but I"m sure a fair amount is. If anything, going after these will help with the "I thought I fixed that" feeling. 

https://github.com/jdphenix/ServUO/commit/63d7f2311566496e3efd41c66199a5438d1c2949

(You'll want to use the raw view)

**Comment by ppardalj** [comment]
Oh my god that's huge.

@jdphenix  can I ask how you generated that report?

**Comment by jdphenix** [comment]
Sure thing. 

The key utility is Jetbrains dupFinder, free and available here: https://www.jetbrains.com/help/resharper/2016.3/dupFinder.html

And the XSL for this program's output, here: https://raw.githubusercontent.com/jdphenix/ServUO/63d7f2311566496e3efd41c66199a5438d1c2949/duptransform.xsl

With those, you can run dupfinder on the command line (this is what I ran to get the Server project output): 

    $ dupfinder /show-text /output="dupReportServer.xml" ".\Server\**.cs"

Then I just fed the output file through an HTML to markdown converter. Any one should do. 

In my professional projects I have this utility running as part of a build step in VSTS, so I can say this definitely can all be automated.

**Comment by ppardalj** [comment]
@jdphenix that's insane!! Awesome job man.

If we ever get to have a real CI pipeline, it would be great to have such thing integrated. But in the meantime having the static report is also extremely valuable. Did you identify some dangerous duplications that should be tackled first?
