### ISSUE TITLE
Pre aos magery spell disruption broken (major issue for pre-aos server owners)

### ISSUE THREAD

**Issue by WiNk-UOFB** [ServUO/ServUO#2113]
When you set the expansion pre-aos: 
T2A / UOR / UOTD / LBR

If you set your currentexpansion.cs to any of these expansion types it makes magery spell disruption stop working. It works perfect with AOS and higher expansions set by default. Its just the pre-aos expansions that its broke on.

**Comment by kevin-10** [comment]
Is this something that was recently broken?

**Comment by WiNk-UOFB** [comment]
Not sure I run a repo from about 5 months ago but I did however download the latest repo about a month ago and the bug was still present on a completely stock servuo.
