### ISSUE TITLE
Light is backed by Direction

### ISSUE THREAD

**Issue by Vorspire** [ServUO/ServUO#2765]
https://github.com/ServUO/ServUO/blob/7153970fa43d371f2a7c7c96da5c132d443dc1f7/Server/Item.cs#L4740

Light has always been backed by the Direction field, but why?

On Multiverse, I changed it to have its own backing field, so that changing the direction of any item does not change its LightType. I have not noticed any adverse effects.

Any clues as to the intention behind this? 
Is it an older client issue? (LightType isn't sent in an old WorldItem packet)
Does anyone have a client old enough to test?

**Comment by kevin-10** [comment]
Maybe when light sources were more scarce, and this would apply to someone holding a torch or a lantern?
