### ISSUE TITLE
Alchemy Crafting Menu

### ISSUE THREAD

**Issue by qbradq** [ServUO/ServUO#277]
Alchemy crafting menu needs to be updated:
* Healing and Curative
  * refresh
  * greater refreshment
  * lesser heal
  * heal
  * greater heal
  * lesser cure
  * greater cure
  * elixir of rebirth
* Enhancement
  * agility
  * greater agility
  * night sight
  * strength
  * greater strength
  * invisibility
* Toxic
  * lesser poison
  * poison
  * greater poison
  * deadly poison
  * parasitic
  * darkglow
  * scouring toxin
* Explosive
  * lesser explosion
  * explosion
  * greater explosion
  * conflagration
  * greater conflagration
  * confusion blast
  * greater confusion blast
  * black powder
  * match cord
  * fuse cord
* Strange Brew
  * smoke bomb
  * hovering wisp
  * natural dye
  * nexus core
* Ingredients
  * plant pigment
  * color fixative
  * crystal granules
  * crystal dust
  * softened reeds
  * vial of vitriol
  * bottle of ichor
  * potash
  * gold dust

**Comment by Ravenwolfe** [comment]
Pull sent. Will still need to create some items:
Nexus Core
Crystal Granules
Potash
Gold Dust
Black Powder
Match Cord
Fuse Cord

Maybe a new issue for these since they are HS stuff.
