### ISSUE TITLE
Anomalous BaseCreature AddItem Override

### ISSUE THREAD

**Issue by Vorspire** [ServUO/ServUO#3217]
https://github.com/ServUO/ServUO/blob/276b5532a3c75b7eeb8078945e6a69843d740085/Scripts/Mobiles/Normal/BaseCreature.cs#L5293

This override may cause anomalous equipment issues.
This override is not present in RunUO.

This override was once also applied to PlayerMobile in ServUO, but was removed at a later date due to issues with BankBoxes.

Recommended update;
Usages of AddItem that are expected to test if the Mobile can equip the given item should be replaced with calls to EquipItem instead.
AddItem behaviour should always result in the item being equipped, regardless of mentioned checks.

**Comment by kevin-10** [comment]
Forcing AddItem to equip the item caused numerous client crashes due to layer conflicts. There are literally hundreds if not thousands of AddItem called when EquipItem should be used. 

Bottom line, forcing an item into a conflicting layer slot causes issues, such as client crashes. BaseCreature seemed to be the only class that this happened consistently. I had it happen on my server to PlayerMobile with some older custom systems where items were force equipped.

So, we can keep as is, and as you mentioned, add sealed, which may have consequences later on down the road for folks with custom stuff regarding their own PlayerMobile, or revert to how it was, and change the tons of AddItem to EquipItem.

**Comment by Vorspire** [comment]
At the end of the day, the mod was never needed and has never been needed until systems that were written badly were introduced. 

The only time AddItem causes layer conflicts is when a developer does not pay attention to the code, such as a vendor which may have an override for a different outfit. 

It should be up to the developer that caused the bug to fix the issue where it stems from, not for someone to have to band-aid it with something that causes even more issues. 

The right way to do it would be to fix the AddItem calls that are problematic and it should not matter how many reference there are to the method. 

Do not trade of quality because of quantity...

At the very least, the mod should be removed from BaseCreature and error logging should be used to warn the developer of their mistake, as is the case with various other implementations - delta queues, packet buffers, non-stackable item amounts changing, missing serialization methods, etc.

All of the extra calls to CheckEquip, CanEquip, etc are redundant, this mod effectively makes AddItem behave like EquipItem and it was never intended.

**Comment by kevin-10** [comment]
I see what your saying. Great learning experience. I'll remove the override, and add error logging via console for any conflicting layers.

**Comment by Vorspire** [comment]
Console and file logging for this case would be preferable since it involves client crashing and should be dealt with as soon as possible.

It will be nice to be able to identify any current stock Mobiles that have conflicting layer issues and get those fixed, I don't think there will be all that many.

**Comment by kevin-10** [comment]
A total respawn, here are the results:

<# 3/30/2018 3:16:48 AM
Offending Mobile: Server.Mobiles.HireMage[0x4542 "Marnina"]
Offending Item: Server.Items.ThighBoots
Layer: Shoes

# 3/30/2018 3:16:48 AM
Offending Mobile: Server.Mobiles.HirePaladin[0x4543 "Kai"]
Offending Item: Server.Items.PlateLegs
Layer: Pants

# 3/30/2018 3:16:50 AM
Offending Mobile: Server.Mobiles.BlacksmithGuildmaster[0x5B2E "Kai"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:16:51 AM
Offending Mobile: Server.Mobiles.HireFighter[0x5E4E "Theron"]
Offending Item: Server.Items.ChainLegs
Layer: Pants

# 3/30/2018 3:16:51 AM
Offending Mobile: Server.Mobiles.Blacksmith[0x5EC5 "Aprille"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:16:51 AM
Offending Mobile: Server.Mobiles.HireFighter[0x602A "Kalkin"]
Offending Item: Server.Items.RingmailLegs
Layer: Pants

# 3/30/2018 3:16:53 AM
Offending Mobile: Server.Mobiles.HireFighter[0x7624 "Zenon"]
Offending Item: Server.Items.BronzeShield
Layer: TwoHanded

# 3/30/2018 3:16:53 AM
Offending Mobile: Server.Mobiles.HireFighter[0x7624 "Zenon"]
Offending Item: Server.Items.LeatherLegs
Layer: Pants

# 3/30/2018 3:16:53 AM
Offending Mobile: Server.Mobiles.HireFighter[0x7625 "Mitexi"]
Offending Item: Server.Items.ChaosShield
Layer: TwoHanded

# 3/30/2018 3:16:53 AM
Offending Mobile: Server.Mobiles.Blacksmith[0x77B3 "Johann"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:16:54 AM
Offending Mobile: Server.Mobiles.Blacksmith[0x7C40 "Iratze"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:16:55 AM
Offending Mobile: Server.Mobiles.Merchant[0x84E1 "Vance"]
Offending Item: Server.Items.FancyShirt
Layer: Shirt

# 3/30/2018 3:16:56 AM
Offending Mobile: Server.Mobiles.Blacksmith[0x8A13 "Doris"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:16:56 AM
Offending Mobile: Server.Mobiles.BlacksmithGuildmaster[0x8A14 "Holt"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x950E "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x950E "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x9511 "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x9511 "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x9512 "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x9512 "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x9513 "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x9513 "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x951B "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x951B "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x951C "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x951C "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x951D "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x951D "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x951E "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x951E "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x95F2 "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x95F2 "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x95F4 "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x95F4 "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x979D "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x979D "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x979E "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x979E "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x979F "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:16:59 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x979F "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x97E5 "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x97E5 "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x97ED "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x97ED "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x990B "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x990B "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x990C "a lava elemental"]
Offending Item: Server.Items.SulfurousAsh
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.LavaElemental[0x990C "a lava elemental"]
Offending Item: Server.Items.LesserPoisonPotion
Layer: Invalid

# 3/30/2018 3:17:00 AM
Offending Mobile: Server.Mobiles.Blacksmith[0x9CB4 "Parnell"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:17:02 AM
Offending Mobile: Server.Mobiles.HireFighter[0xA69F "Zann"]
Offending Item: Server.Items.ChainCoif
Layer: Helm

# 3/30/2018 3:17:02 AM
Offending Mobile: Server.Mobiles.HireFighter[0xA69F "Zann"]
Offending Item: Server.Items.ChainLegs
Layer: Pants

# 3/30/2018 3:17:02 AM
Offending Mobile: Server.Mobiles.Blacksmith[0xA6EA "Herman"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:17:03 AM
Offending Mobile: Server.Mobiles.Blacksmith[0xA9C9 "Zeke"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:17:03 AM
Offending Mobile: Server.Mobiles.Miner[0xACD4 "Nicia"]
Offending Item: Server.Items.FancyShirt
Layer: Shirt

# 3/30/2018 3:17:03 AM
Offending Mobile: Server.Mobiles.Miner[0xACD4 "Nicia"]
Offending Item: Server.Items.ThighBoots
Layer: Shoes

# 3/30/2018 3:17:04 AM
Offending Mobile: Server.Mobiles.BlacksmithGuildmaster[0xB0BB "Juliana"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:17:04 AM
Offending Mobile: Server.Mobiles.Miner[0xB18C "Reyhan"]
Offending Item: Server.Items.LongPants
Layer: Pants

# 3/30/2018 3:17:04 AM
Offending Mobile: Server.Mobiles.Miner[0xB18C "Reyhan"]
Offending Item: Server.Items.ThighBoots
Layer: Shoes

# 3/30/2018 3:17:04 AM
Offending Mobile: Server.Mobiles.Blacksmith[0xB4ED "Roth"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:17:04 AM
Offending Mobile: Server.Mobiles.Blacksmith[0xB596 "Pantzike"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:17:05 AM
Offending Mobile: Server.Mobiles.HirePaladin[0xB66B "Beaman"]
Offending Item: Server.Items.PlateLegs
Layer: Pants

# 3/30/2018 3:17:05 AM
Offending Mobile: Server.Mobiles.Thief[0xB6E9 "Una"]
Offending Item: Server.Items.Shirt
Layer: Shirt

# 3/30/2018 3:17:05 AM
Offending Mobile: Server.Mobiles.Thief[0xB6E9 "Una"]
Offending Item: Server.Items.LongPants
Layer: Pants

# 3/30/2018 3:17:05 AM
Offending Mobile: Server.Mobiles.Thief[0xB6E9 "Una"]
Offending Item: Server.Items.ThighBoots
Layer: Shoes

# 3/30/2018 3:17:07 AM
Offending Mobile: Server.Mobiles.Merchant[0xC307 "Magdalen"]
Offending Item: Server.Items.FancyDress
Layer: OuterTorso

# 3/30/2018 3:17:07 AM
Offending Mobile: Server.Mobiles.HireFighter[0xC532 "Royce"]
Offending Item: Server.Items.ChainCoif
Layer: Helm

# 3/30/2018 3:17:07 AM
Offending Mobile: Server.Mobiles.HireFighter[0xC532 "Royce"]
Offending Item: Server.Items.ChainLegs
Layer: Pants

# 3/30/2018 3:17:07 AM
Offending Mobile: Server.Mobiles.HireFighter[0xC533 "Alistair"]
Offending Item: Server.Items.WoodenShield
Layer: TwoHanded

# 3/30/2018 3:17:07 AM
Offending Mobile: Server.Mobiles.HireFighter[0xC533 "Alistair"]
Offending Item: Server.Items.ChainCoif
Layer: Helm

# 3/30/2018 3:17:07 AM
Offending Mobile: Server.Mobiles.HireFighter[0xC533 "Alistair"]
Offending Item: Server.Items.ChainLegs
Layer: Pants

# 3/30/2018 3:17:08 AM
Offending Mobile: Server.Mobiles.HireFighter[0xCE32 "Letha"]
Offending Item: Server.Items.ChainCoif
Layer: Helm

# 3/30/2018 3:17:08 AM
Offending Mobile: Server.Mobiles.HireFighter[0xCE33 "Reginald"]
Offending Item: Server.Items.StuddedLegs
Layer: Pants

# 3/30/2018 3:17:10 AM
Offending Mobile: Server.Mobiles.BlacksmithGuildmaster[0xD8BE "Loretta"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:17:10 AM
Offending Mobile: Server.Mobiles.Merchant[0xD9C5 "Eliska"]
Offending Item: Server.Items.FancyDress
Layer: OuterTorso

# 3/30/2018 3:17:11 AM
Offending Mobile: Server.Mobiles.HireFighter[0xDD10 "Mackenzie"]
Offending Item: Server.Items.ChaosShield
Layer: TwoHanded

# 3/30/2018 3:17:11 AM
Offending Mobile: Server.Mobiles.HireFighter[0xDD10 "Mackenzie"]
Offending Item: Server.Items.StuddedLegs
Layer: Pants

# 3/30/2018 3:17:12 AM
Offending Mobile: Server.Mobiles.IronWorker[0xE526 "Cyril"]
Offending Item: Server.Items.FullApron
Layer: MiddleTorso

# 3/30/2018 3:17:12 AM
Offending Mobile: Server.Mobiles.IronWorker[0xE526 "Cyril"]
Offending Item: Server.Items.Bascinet
Layer: Helm
>

**Comment by kevin-10** [comment]
Tons of conflicting layers. Mainly in derived BaseVendor scrips.  BaseVendor uses SetWearable function which checks for conflicts, so any deriving method should call the base last.

**Comment by kevin-10** [comment]
This has been complete, not sure how to mark it as such.
