### ISSUE TITLE
Suggestion: Honesty sites

### ISSUE THREAD

**Issue by Nerun** [ServUO/ServUO#3242]
Hi there,

About "reticulating spines", the way ServUO look for honesty sites to spawn items, it took too long. I know there is a good option in Config folder to disable it. What is awesome for developers. But, and i don't know if it is possible, as a future improvement if, instead of recalculating the honesty sites every time the server starts, if it first analyzes the hashes of the files it uses to calculate (using md5sums or any software like this) to verify if there was any change, it would not need to recalc every start, but just when needed.

**Comment by Vorspire** [comment]
It's still much faster than the original implementation. 
It takes a while on a desktop PC, but not so long on a typical dedicated server with 8 cores.
My PC is trash and it can complete the task in around a minute. 

Hashing/caching could cause inconsistencies in the system if for example, Regions.xml was edited (Towns added or removed), or if the MUL/UOP map files change, if new dynamic regions are instantiated during world load, etc. 

I recommend simply disabling the system for local testing, by all means you can take a whack at optimising it further, but running the map files through a checksum generator is probably going to negate the time benefit gained from the caching.

**Comment by Vorspire** [comment]
"Reticulating Splines" is a throw-back to Sim City 2K ;)

**Comment by DarkLotus** [comment]
Cant really speed it up much i dont think, from my look at it the inner loops use Ultima.dll to read the landtile's. So cant really multi thread it without rewriting ultima dll to be thread safe.

**Comment by Vorspire** [comment]
It is actually already multi threaded, I uses the Task Parallel Library to split the map into sections and each section is processed asynchronously.

**Comment by Nerun** [comment]
I thin we can close this issue. Anyway, i wrote a tutorial:
https://www.servuo.com/tutorials/linux-mono.40/
