### ISSUE TITLE
Quest Button at Paperdoll

### ISSUE THREAD

**Issue by Nerun** [ServUO/ServUO#3252]
Hi there,

At paperdoll, there is a button called Quest. When you click in it is supposed to open the Quest Log. Actually it open the quest log, but thare's nothing on it (empty), independent if you are currently in a quest or not.

This bug comes from RunUO. At RunUO i have fixed it adding this code to QuestSystem.cs:

```
using System;
using System.Collections;
using System.Collections.Generic;
using Server;
using Server.Items;
using Server.Gumps;
using Server.Mobiles;
using Server.Network;
using Server.ContextMenus;

namespace Server.Engines.Quests
{
// Nerun's Distro Addition -- 1 of 1 --begin
	public class QuestButton
	{
		public static void Initialize()
		{
			EventSink.QuestGumpRequest += new QuestGumpRequestHandler( EventSink_QuestGumpRequest );
		}

		private static void EventSink_QuestGumpRequest( QuestGumpRequestArgs args )
		{
			PlayerMobile pm = args.Mobile as PlayerMobile;

			if( pm == null )
				return;

			QuestSystem qs = pm.Quest;

			if( qs != null )
				qs.ShowQuestLog();
		}
	}
// --------------------------------------end
        public delegate void QuestCallback();
```

In RunUO, with this code when i press QUEST button gonna open two logs: the default one, that is always empty and the current quest log.

I have tried it ar ServUO, but no success.

**Comment by kevin-10** [comment]
The old quest system gump is opened via context menu. The quest button on the paperdoll opens the mondains quest system.
