### ISSUE TITLE
[HOUSE] Retrieve Context Option

### ISSUE THREAD

**Issue by qbradq** [ServUO/ServUO#352]
On OSI there is a "Retrieve" option on secured items in houses. Selecting this
menu option unlocks the item and drops it in your pack as long as it isn't too
heavy or doesn't put too many items in your own pack.

**Comment by Vorspire** [comment]
Does this apply to Lockdowns, or only Secure Lockdowns?

It seems there is no extensible code to cover this for all items - looking at BaseHouse.SetSecureLevelEntry may be the key, but it is only called by specific items - none of which are things like clothing and armor.
