### ISSUE TITLE
Detach the servuo process from the console

### ISSUE THREAD

**Issue by YuGiOhJCJ** [ServUO/ServUO#369]
Hello,
When I run ServUO, it is by default in interactive mode.
It means that the process is attached to the console and no other command can be executed after this one.
I would like to run ServUO in background because my console is not dedicated to this application only (I run other services too).
I tried to add the well-known "&" character at the end of the command line but if I do that, I got an exception:

`$ mcs -target:library -out:Ultima.dll -r:System.Drawing.dll -d:ServUO -nowarn:0618,0219,0414,1635 -debug -nologo -optimize -unsafe -recurse:Ultima/*.cs`

`$ mcs -win32icon:Server/servuo.ico -r:Ultima.dll,System.Drawing.dll -nowarn:0618,0219,0414,1635 -target:exe -out:ServUO.MONO.exe -d:ServUO -d:MONO -debug -nologo -optimize -unsafe -recurse:Server/*.cs`

`$ mono ServUO.MONO.exe&`

So, is there a way to detach the ServUO process from the console?
Thank you.
Best regards

**Comment by dmurphy22** [comment]
Use screen.

screen ./ServUO.MONO.ese

**Comment by YuGiOhJCJ** [comment]
That's not exactly what I want.
My services are run automatically (without a human).
It means that there is a script that runs each services.
For example, myscript.sh content:
```
# Run the minetest server
killall minetestserver
HOME=/home/yugiohjcj
cd /home/yugiohjcj
sudo -u yugiohjcj minetest --server &
# Run the chocolate server
killall chocolate-server
sudo -u chocolate /usr/games/chocolate-server -servername "YuGiOhJCJ's server" &
```
If I use screen like you propose, that is the new content of myscript.sh:
```
# Run the minetest server
killall minetestserver
HOME=/home/yugiohjcj
cd /home/yugiohjcj
sudo -u yugiohjcj minetest --server &
# Run the servuo server
cd /home/yugiohjcj/ServUO-a0b40d40a6c8ec3c33f9e981ed735cda1ad927ec
screen mono ServUO.MONO.exe
# Run the chocolate server
killall chocolate-server
sudo -u chocolate /usr/games/chocolate-server -servername "YuGiOhJCJ's server" &
```
Do you see what will be the result?
The minetest server is run, then the servuo server is run (through the screen command).
The screen command is attached to the console, so the chocolate server will never be run.
This does not solve my problem.
Any other idea?

**Comment by dmurphy22** [comment]
You can start a screen instance in detached mode by appending -d

screen -d ./ServUO.MONO.exe

**Comment by qbradq** [comment]
Sorry man, this is the only way. We really stink at supporting The Unix Way :(

**Comment by YuGiOhJCJ** [comment]
dmurphy22> Not really. In the manual of screen it is not written that the '-d' option is not starting a screen instance in detached mode. This option detaches an existing instance of screen.
So, the result is:
$ screen -d mono ServUO.MONO.exe
There is no screen to be detached.
Unfortunately, it does not solve the problem.

**Comment by bsenyuva** [comment]
Hi, can you try
`screen -dmS servuo ServUO.sh`

**Comment by YuGiOhJCJ** [comment]
Nice!
I did:
```
screen -dmS servuo mono ServUO.MONO.exe
```
And what is good is that I can do:
```
$ screen -d -r
```
In order to reattach it.
Then I do Ctrl + A then Ctrl + D in order to detach it again.
That's perfect.
Thank you a lot.
Problem solved.

**Comment by bsenyuva** [comment]
You are welcome :)

In fact if you need to check is process still working via bash script, you can use:

`screen -ls | grep servuo`

You can use any name instead of servuo, such as MyWonderfulShard. It's just an identifier.
