### ISSUE TITLE
Enhanced Client: Character Creation Stuck

### ISSUE THREAD

**Issue by LordFenris** [ServUO/ServUO#3776]
The latest version of the game and SVN
After implementing the package of recent changes in SVN (housekeeping), there was a problem of creating new characters in the Enhanced client. After configuring a new character, you can not log into the game world (stuck on the window with the title text Ultima Online - before entering the game world). However, you can log in to existing characters, and created using a 2D account.
Previously, this problem did not occur

**Comment by pechorin** [comment]
Same issue with classic client (but stucked right after server select list)

**Comment by Tasanar** [comment]
Yes I have had this reported twice on my shard as well. Except they created a character, EC, logged in and got connection lost right away. Once after they created a 2nd character did it let them in. Very very strange.

**Comment by kevin-10** [comment]
Not sure, verified on my end.  @Vorspire, any insight on this? I see some changed made to packet handlers regarding login.  Seems to only happen on creating a new character.
