### ISSUE TITLE
Animal Training - bugs noticed in pets slots,etc.

### ISSUE THREAD

**Issue by LordFenris** [ServUO/ServUO#3778]
We have recently investigated a alot of pet in terms of number of slots / scaling stats after taming (GMs generated group of each pets and checked their parameters, comparing data with a fresh source (below) + Stratics Wiki
http://www.uoguide.com/Tameables
and here are the errors we have noticed in this regard:
1) Lasher : 1-3 slots (currently has 2-4)
2) Imp: 2-4 slots (currently has 3-4)
3) Nightmare: 2-5 slots (currently has 3-5)
4) Paralithode - A unique pet should have AI NINJA and attack from hiding
5) Giant Ice Worm - should not cut stats
6) Hell Hound - DEX / STAMINA should be cut in half
7) Stone Slith - this is a battle version of Slith and should not have Dragon Breath
8) Toxic Slith - it is not possible to tame it but we checked it, it should have poisoning and it does not have it (https://stratics.com/w/index.php?title=UO:Toxic_Slith)
9) White Wyrm: 3-5 slot (currently has 4-5) 
10) Wild Tiger - he should have Bleed and Grasping Claw but he has Bleed and Healing
11) Windrunner: 1-3 slots (currently has 2-4) 
Probably nothing - from things noticed - I did not miss :)

**Comment by kevin-10** [comment]
Windrunner was changed to match other store bought mounts:

https://uo.com/wiki/ultima-online-wiki/publish-notes/publish-100/

**Comment by kevin-10** [comment]
*Lasher and windrunner and other store bought mounts are 2 - 4:
https://uo.com/wiki/ultima-online-wiki/publish-notes/publish-100/

*What says Paralithode is ninja AI?

*Giant Ice Wyrm does not cut stats.

*White Wyrms have a very low chance to spawning with 3.

*What says hellhounds lose half dex/stam?

**Comment by LordFenris** [comment]
As for Paralithode - our GM described this issue based on an unofficial source (forum) - sorry for the confusion :)

**Comment by LordFenris** [comment]
_*Giant Ice Wyrm does not cut stats._
I wrote about Giant Ice Worm - not a Wyrm :)

**Comment by kevin-10** [comment]
Really?  These have pretty weak stats.

**Comment by LordFenris** [comment]
Yap:) Look at this sshot:
https://s33.postimg.cc/b649g5w5r/Giant_Ice_Worm.jpg
