### ISSUE TITLE
Cu Sidhe and Hiryu INT stat lost 

### ISSUE THREAD

**Issue by LordFenris** [ServUO/ServUO#3780]
We have several signals last weekend about INT statlost after taming in case of some pets. Players signaled that on EA, in the case of some stronger animals, after taming, the pet actually loses half of strength and dex, but this does not apply to intelligence.

At the moment (current SVN) , the problem is to concern Cu Sidhe (INT and mana cut) and a Hiryu (INT cut without mana). 

Looking at the information at the following links - in fact, INT (and mana) was not reduced from the base pet value.
https://stratics.com/threads/cu-sidhe-builds.395055/
https://stratics.com/threads/hiryu-stats.397808/

**Comment by kevin-10** [comment]
We had one recently bumbed the int up to 500.  I guess this is so you can only take the other stats up so high before they reach their overall cap in animal training.  This is fine, and we can adjust as we go. I knew, when this system was written, it was impossible to get all these behind the scene changes in all at once.
