### ISSUE TITLE
Giant beetle and bond taming requirements

### ISSUE THREAD

**Issue by LordFenris** [ServUO/ServUO#3784]
The problem concerns Giant Beetle bonding by players without animal taming. They receive a message about the lack of the required amount of Animal Taming to bond - despite waiting for 7 days with full feeding.

OSI:
https://uo.com/wiki/ultima-online-wiki/gameplay/a-guide-to-pack-animals/
"Anyone can bond with a pack animal (or any animal with a minimum taming requirement of 29.1 or below) regardless of their skill level in taming" 

"There are, at this time, three creatures in game that may be used by all to carry items. These are the Pack Horse, the Pack Llama and the Giant Beetle. Each of these creatures are capable of bonding with their owner and will therefore recall with the owner, negating the need to cast gate spell. In addition necromancers are able to summon a horde minion which can also be used to provide extra carrying capacity for its owner"

**Comment by kevin-10** [comment]
Once you begin training, any binding requirement overrides get taken away.

**Comment by LordFenris** [comment]
Do I understand correctly that if the pet has not yet been trained by these players, then they should start this training and then AT requirements for bonding will be - for these pets - removed?  Will try, thanks for an info :)

**Comment by LordFenris** [comment]
Hmmm, We looked more closely at these animals. 
For the indicated beetle, the training procedure has not been started - it is not available because both players do not have AT / AL. Tamer, who tamed both beetle before handing the animals to the craftsmen, also did not train animals.

The problem de facto concerns the possibility of bonding this type of animal without possessing AT, because for these pets the possibility of bond, should not depend on the possession of this ability.

**Comment by kevin-10** [comment]
I don't know what AT / AL means.

Also, what is the taming requirement on the offending creatures?

**Comment by LordFenris** [comment]
AT/AL - Animal Taming /Lore
Taming requirement
Giant Beetle/Pack Horse and Pack Llama - 29.1 
Source 
http://www.uoguide.com/Tameables

**Comment by kevin-10** [comment]
They should be able to bond.
