### ISSUE TITLE
Dead players unable to move through moveable impassables

### ISSUE THREAD

**Issue by Vlek** [ServUO/ServUO#381]
In the [PlayerMobile.cs](https://github.com/ServUO/ServUO/blob/master/Scripts/Mobiles/PlayerMobile.cs#L1640):

`

			if (!Alive)
			{
				MovementImpl.IgnoreMovableImpassables = true;
			}

			res = base.Move(d);

			MovementImpl.IgnoreMovableImpassables = false;`

Should be changed to:

`

			MovementImpl.IgnoreMovableImpassables = false;

			if (!Alive)
			{
				MovementImpl.IgnoreMovableImpassables = true;
			}

			res = base.Move(d);`

**Comment by qbradq** [comment]
The ghost body should handle this for us. When I test I am able to pass through doors and footstools as a ghost but not alive. Can you give me an example?

**Comment by Vlek** [comment]
Honestly, I didn't check it in game. I just noticed this while I was changing things for my shard and thought it was bad coding at the very least.

**Comment by qbradq** [comment]
Yea, it is :)
