### ISSUE TITLE
Gargoyle WIngs and Consecrate Weapons

### ISSUE THREAD

**Issue by LordFenris** [ServUO/ServUO#3812]
With the gargoyle (Wings) on the gargoyle, Consecrate Weapon is not working properly.
- Does not hit the lowest immunity target (the player has a 100% proc chance)

It looks like:
Player beat the target with a high Physical Resist (over 80), has a 100% phys damage weapon, so do a little damage.
Throwing Consecrate Weapon.
If got wings - >> damage has not changed and still dealing a tiny damage ...
After removing the wings - >> high damage!
Re-inserting wings - >> low damage ....
Hence the conclusion that the assumed Wings block the effect of Consecrate Weapon

**Comment by kevin-10** [comment]
Who is wearing the wing armor?  The one hitting or getting hit?

**Comment by LordFenris** [comment]
The hitting player.

**Comment by kevin-10** [comment]
Can you see if the same is true when wearing a quiver?
