### ISSUE TITLE
BOD Combine Problem

### ISSUE THREAD

**Issue by Argalep** [ServUO/ServUO#3816]
Small bod was made to combine large bod. If you want to combine errors.

"That is not a bulk order for this large request"

![3](https://user-images.githubusercontent.com/17765272/44627109-f7758a80-a930-11e8-8374-87b904dd182a.jpg)

![4](https://user-images.githubusercontent.com/17765272/44627110-f7758a80-a930-11e8-9be3-9866b48aa143.jpg)

![5](https://user-images.githubusercontent.com/17765272/44627108-f6dcf400-a930-11e8-825c-521fbf474b4b.jpg)

**Comment by kevin-10** [comment]
Fucking tinker bods, I'll tell ya!
