### ISSUE TITLE
Piracy and NPC ships boarding problems

### ISSUE THREAD

**Issue by LordFenris** [ServUO/ServUO#3822]
We noticed a mechanic error related to boarding NPC ships (piracy).
Despite defeating the NPC ship, players can not get to the defeated unit.
From our tests, the result that the reason for this situation is the setting of security levels for these NPC ships, similar to what happens on the ships of players
https://cdn.discordapp.com/attachments/474863813246713856/483750884325457928/2.jpg

After making the change - from the GM level - the status of  access to public - boarding was possible.

Pirates GUIDE on OSI:
https://www.youtube.com/watch?v=_dLvScYfNfU

**Comment by LordFenris** [comment]
We will try additional test first

**Comment by LordFenris** [comment]
Unfortunately, despite talking to Bigglesby, the players were still unable to board at sea via mooring line [ look at OSI film - 31:15) .They only managed it from land. 
An attempt to board from the own ship ends with the message that it can not be done while at home or on a ship..  
I am opening the application again.

**Comment by kevin-10** [comment]
Did you scuttle the boat?

**Comment by Tasanar** [comment]
https://trueuo.com/index.php?forums/servuo-bug-reports.75/

Just until ServUO comes up you can use this link to also report bugs. Dexter and Argalep have the links and check it. Everything new gathered here will be ported over to ServUO when it comes online.

**Comment by kevin-10** [comment]
Code looks good. The boat needs to be scuttled to board.  This is true for EA.

**Comment by kevin-10** [comment]
Confirmed, works as intended. You need to scuttle the boat to board.
