### ISSUE TITLE
servuo.com down?

### ISSUE THREAD

**Issue by Ugdhar** [ServUO/ServUO#3830]
I haven't been able to get to servuo.com for days now, and haven't been able to drum up any info on why. Is it gone?

**Comment by Tasanar** [comment]
ServUO will hopefully be back up in a week or two.

It is an issue that staff is tracking and working to resolve.

In the mean time we are still developing the emulator and posting new fixes.

You can report bugs here on Github or here: https://trueuo.com/index.php?forums/servuo-bug-reports.75/

You can also join the Discors ServUO chat channel.
