### ISSUE TITLE
C# 6 support in scripts

### ISSUE THREAD

**Issue by ggobbe** [ServUO/ServUO#4122]
I noticed that it is possible to add support for C# 6 which has quite a bunch of nice features (string interpolation, null check propagation, ...).

I made the changes required for basic support there https://github.com/ggobbe/ServUO/commit/e588735d44d0923796cf824f912a1c8be408db4c

But for some reason the roslyn directory at the root needs to be moved under a bin\ directly at the root to run ServUO.exe

Also, I am not sure if that would work with Mono on Linux.

Could someone look into it and if possible add the support for C# 6 to the scripts compiler?

Thanks

**Comment by Argalep** [comment]
https://github.com/ServUO/ServUO/pull/4133

**Comment by dmurphy22** [comment]
Implemented in 0d919952884509dce08bebe91cb72644b046b6bb
