### ISSUE TITLE
Deserialization issue

### ISSUE THREAD

**Issue by ggobbe** [ServUO/ServUO#4143]
One of these two commits broke the loading of our world: 

a4afe616e465634864c6d959c5680ec627d4c107
92482089233573af2b69a564f6c52562955b7ea9

![image](https://user-images.githubusercontent.com/2607273/49810905-77015b00-fd62-11e8-8f81-18682e4fd8a4.png)

**Comment by kevin-10** [comment]
If it’s just the rot worm, let them delete as they will respawn.

**Comment by ggobbe** [comment]
Does it not mean that someone is reading the wrong data to write in the wrong property?

Even if I delete the Rotworm, it means that another objet will be incorrectly initialized I think.

**Comment by kevin-10** [comment]
9248208 has been reverted due to this issue.
