### ISSUE TITLE
Detect Hidden does not reveal hidden target when Notoriety with source is Innocent

### ISSUE THREAD

**Issue by ggobbe** [ServUO/ServUO#4229]
When using the Detect Hidden skill, it does not reveal hidden players if the notoriety between the target (hidden player) and the source (detect hidden caster) is Innocent.

That is because `DetectHidden.CanDetect(src, target)` uses `Server.Spells.SpellHelper.ValidIndirectTarget(target, src)` and the last statement of this method is `return (Notoriety.Compute(@from, to) != Notoriety.Innocent || @from.Murderer);`.

As a temporary fix on my end I added an optional bool to the `ValidIndirectTarget` method to ignore the notoriety check: 
```public static bool ValidIndirectTarget(Mobile from, Mobile to, bool ignoreNotorietyCheck = false)```

And it then returns:
```return ignoreNotorietyCheck || (Notoriety.Compute(@from, to) != Notoriety.Innocent || @from.Murderer);```

**Comment by kevin-10** [comment]
That's how it tested on EA when this issue was addressed a while back. Unless your red, you're not going to reveal a blue player.

**Comment by ggobbe** [comment]
Ok thanks, I did not read anything about it on uoguide.com hence the question. 
Thanks for clarifying.
