### ISSUE TITLE
Pet Training

### ISSUE THREAD

**Issue by fdesur** [ServUO/ServUO#4309]
Hi there,
Im new here i would like to help to show some bugs about pet system training.
I love the system anyway!

I think i discovered a few bugs. Source http://www.uoguide.com/Pet_Training

1.- Hiryu i can train her twice or more (depends on free slots)
2.- Pets stats don't gain naturally.( Str, Agi, Int )
3. If i choose set up strengh on the pet menu doesn't change the hits,  the same with Agi (stamina) and Int (mana).

Regards!

**Comment by kevin-10** [comment]
Neither of these are bugs.
