### ISSUE TITLE
Rock barrier in Treasures of Kotl not working correctly

### ISSUE THREAD

**Issue by kevin-10** [ServUO/ServUO#4347]
After not being used for a while, it seems to have been detached from WheelOfTime.

**Comment by kevin-10** [comment]
https://github.com/ServUO/ServUO/blob/5a48eff11695ff8d64ad9305faa128615f7faffe/Scripts/Services/Seasonal%20Events/TreasuresOfKotlCity/Items/WheelsOfTime.cs#L124-L127

**Comment by kevin-10** [comment]
TODO: Check for one that exists, and move new one to world at proper location.

**Comment by Tasanar** [comment]
So after deleting the wall and running the Simulation it worked great.

The new problem is the Wheel of time does not re-set after the encounter ends and just keeps spinning.

**Comment by Tasanar** [comment]
The wall re-set correctly but the WheelOfTime just keeps going and says "The wheels of time have been activated already"

**Comment by kevin-10** [comment]
https://github.com/ServUO/ServUO/blob/5a48eff11695ff8d64ad9305faa128615f7faffe/Scripts/Services/Seasonal%20Events/TreasuresOfKotlCity/Items/WheelsOfTime.cs#L72

This needs to be added to the CleanUp() method. It was being bypassed and causing it to not be re-set. this would occur if you restarted the shard around the 2 hour re-set period (when it would hav ebeen reset).
