### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by youhide** [ServUO/ServUO#4367]
How about migrate it to .NET Core?

**Comment by dmurphy22** [comment]
That would likely be an incredibly difficult task but is something I have been researching. It might happen in the future but not any time soon and if it did happen, because ServUO's codebase is so monolithic it would not be considered stable for quite a while.

Closing for now.

**Comment by kamronbatman** [comment]
@youhide, check out [ModernUO](https://github.com/modernuo/modernuo) which targets .NET Core 3.0. :)
