### ISSUE TITLE
(mono) restart command causes crash followed by endless restart loop

### ISSUE THREAD

**Issue by Zavreyon** [ServUO/ServUO#4398]
This has occurred on both 56.0 release and a git clone taken today. Debian 9.9 x64 with mono 5.20.1.19. 

[Crash 14-5-2019-14-47-28.log](https://github.com/ServUO/ServUO/files/3178496/Crash.14-5-2019-14-47-28.log)

Occurs with no modifications to core, scripts, or config except Datapath to point to Muls. Happens when using the restart command both from server console and from ingame. 

14:47:28 Error:
14:47:28 System.IO.IOException: Invalid handle to path "/srv/ServUO/latest/[Unknown]"
  at (wrapper managed-to-native) System.Runtime.Remoting.Messaging.AsyncResult.Invoke(System.Runtime.Remoting.Messaging.AsyncResult)
  at System.Runtime.Remoting.Messaging.AsyncResult.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <6649516e5b3542319fb262b421af0adb>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <6649516e5b3542319fb262b421af0adb>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <6649516e5b3542319fb262b421af0adb>:0
14:47:28 Crash: Generating report...done
14:47:28 Crash: Backing up...done
14:47:28 Crash: Restarting...done

I do not appear to be the only one having this issue as indicated by these forum posts:
https://www.servuo.com/threads/on-unix-console-a-server-restart-creates-an-endless-loop.10964/
https://www.servuo.com/threads/restart-servuo-crash-linux.10991/

**Comment by Zavreyon** [comment]
When using mono 6.0 preview release, I get a bit more in the crashlog, don't know if any of this helps or not:

[Crash 24-6-2019-15-53-44.log](https://github.com/ServUO/ServUO/files/3321614/Crash.24-6-2019-15-53-44.log)

**Comment by kevin-10** [comment]
I highly doubt you'll find any mono support here.

**Comment by Zavreyon** [comment]
I understand, I have since found a workaround using screen and systemd that allows server restarts without the loop occurring.

**Comment by kamronbatman** [comment]
FYI this has not been fixed still.

**Comment by TrueUO** [comment]
Yeah, as Dexter pointed out above almost no one on the current team has any experience with Mono. **We currently require someone from within the community to take up the extra support for other OS.** @kevin-10 @Argalep and I have no experience with any other OS, other than windows.

**Comment by kamronbatman** [comment]
It isn't the ServUO code per se, it is mono. Mono doesn't work that well for a project like this. It was never made to support this use case.

At any rate, handling restarts properly will need some mono pragmas and custom case logic. Unfortunately I don't support mono even though I exclusive use osx because it's buggy and doesn't have parity with .net framework.
I highly recommend dropping mono support entirely.

**Comment by TrueUO** [comment]
Fixed.

Thanks @pyro17
