### ISSUE TITLE
[BUG] Reforging with HRSK works as spined

### ISSUE THREAD

**Issue by Czekos** [ServUO/ServUO#4425]
It should be possible to reforge a leather armor with HRSK to get luck between 120-150 or most probably 130-150. Now it works as spined (only up to 120 of luck).Currently 

HOW TO RE-PRODUCE:
1) Create some expectional leather armors (ex. caps) with a normal leather and a normal sewing kit.
2) Double click HRSK and target a leather piece.
3) Choose / Toggle:
 - Powerful Re-forging
 - Grand Artifice
 - Inspired Artifice
 - Choose name: Auspicious / Of Fortune

4) Reforge

Reforged items should have a luck property with value between 120-150.

The LuckTable:
https://github.com/ServUO/ServUO/blob/84ae0c64a6dbce728553d467b7e6b1eccb6ea603/Scripts/Services/LootGeneration/RunicReforging/RunicReforging.cs#L2749-L2757

Currently for HRSK the GetResourceIndex() returns 3 and the GetPrerequisiteIndex() 1. It means that from Luck table we get min value = 100 and max = 120 (in the class NamedInfoCol - methods Min/Max). In the end we get the same values for SRSK and HRSK, which is wrong.

https://github.com/ServUO/ServUO/blob/84ae0c64a6dbce728553d467b7e6b1eccb6ea603/Scripts/Services/LootGeneration/RunicReforging/RunicReforging.cs#L801-L852

If the GetResourceIndex() for HRSK would return 2 then everything would be fine, but I only checked it for LUCK property and I'm not sure if the index should be modificated for all other properties. Probably yes and the same for BRSK.

**Comment by kevin-10** [comment]
We're going off these charts:

https://uo2.stratics.com/items/magic-item-properties/runic-re-forging/semmersets-re-forging-charts/

I spent an enormous amount of testing. Powerful on its own will NOT produce 150 luck. You cannot reforge auspicious/of fortune with horned/barbed so that's moot.

**Comment by Czekos** [comment]
@kevin-10 Aren't you surprised by the fact that there are no HRSK and BRSK among these charts at all? The fact that they are not there means for you that you can not reforge at all? The Last modified of the document you posted is July 24, 2012 and it was created based on the charts provided in one of the threads on forum.... people were requesting it one by one and not for everything - in the end someone placed it in one place, but these are not all possibilities. 

1) You can reforge auspicious/of fortune with HRSK, but not BRSK.

2) With your current implementation even with SPINED it's not possible to get luck between 100 and 120. It's always 100 or 120 - which is wrong. The charts are just showing MAX value. That's the whole point of reforging - you reforge until you get a perfect piece with max value. 

3) With HORNED you should be able to get leather with LUCK between 120 - 150 without brittle.

**HOW TO MAX LUCK SUIT**
https://stratics.com/threads/how-to-craft-max-luck-suit-step-by-step.348530/ - one of the steps is to use PoF to get 255 durability - so it cannot be brittle.

**EXAMPLES HERE:**
Look here: https://stratics.com/threads/dexxer-luck-suit-2-legendary-rings.346044/

And here: https://stratics.com/threads/full-mage-luck-suit.302888/

And here: https://stratics.com/threads/reforging-a-luck-suit-for-melee.331213/

**Comment by kevin-10** [comment]
ok, so on EA, powerful won't let you choose auspicious/of fortune, however if you craft without powerful, you'll get the 120-150 range.

**Comment by kevin-10** [comment]
Many of the options weren't canceling the correct prefix/suffix names out as well.

**Comment by kevin-10** [comment]
This issue should now be fixed.

**Comment by Czekos** [comment]
@kevin-10 Could you please paste here a link to commit?
