### ISSUE TITLE
Cooking gains/mat losses

### ISSUE THREAD

**Issue by ShadwDrgn** [ServUO/ServUO#4429]
When cooking stacks of food at a time, only one item should be lost on failure. Additionally on success you should gain an amount of skill as though each item in the stack was crafted seperately. This was tested on Sonoma, 6/10/2019. Screenshot is of 3 failures an one success on a stack of 136 raw chicken. It is now 133 cooked. For further reference uoguide suggests doing stacks of bbq due to the large gains all at once:
[UOGuide:Cooking](http://www.uoguide.com/Cooking)

![ss_cooking](https://user-images.githubusercontent.com/2470781/59233179-6b79da00-8bb5-11e9-8146-db9e2316fc51.png)

**Comment by kevin-10** [comment]
Try this now, let me know.

**Comment by ShadwDrgn** [comment]
Testing with one stack this is SUPER close. It could be right. It SEEMS like there is no skill gain on a fail, when there should be ONE skill check on a failure still. I may have just gotten unlucky and not seen the gain. Though I tested through about 10-15 failures at only 15.9 just as i tested on official in this screenshot. At that low of a level I should still get gains from failures. Though only the one gain rather than for the whole stack, of course.
