### ISSUE TITLE
AI Targeting/Attacking preference

### ISSUE THREAD

**Issue by ShadwDrgn** [ServUO/ServUO#4430]
On official, when a player is sharing the same tile as their Pet/Summon, any mobs that are looking for someone to focus/attack will 100% of the time choose the pet over the controller of the pet when it is a decision between the two. This has been tested on sonoma, atlantic, and TC with balrons, miasma, swoop, nightmares, dragons, greater dragons, hiryu, lesser hiryu, ninjas, spiders, and many many other mobs. Please let me know if there is any kind of data I can provide to help.

On ServUO mobs can target controller in same tile as pet.

This has been the case since at least the release of SE, probably longer.

**Comment by kevin-10** [comment]
This issue has been fixed.
