### ISSUE TITLE
Yomatsu mines

### ISSUE THREAD

**Issue by ShadwDrgn** [ServUO/ServUO#4437]
Yomatsu mines should be a no recall zone to be consistent with official. Currently it's a no mark zone, but you should also be unable to recall from the area.

Just in case I'm calling this the  wrong thing (can't find references to "yomatsu" in region files) it's the mines that the fire beetle is found in south east of the homare moongate

**Comment by kevin-10** [comment]
Can you recall from fan dancer's dojo?
