### ISSUE TITLE
database?

### ISSUE THREAD

**Issue by ac1dr3d** [ServUO/ServUO#4538]
Hi
I know this question could be asked millions of times already but...
Id like to hear answer from you... developers of this repo.

Is it too hard to move from xml to database?

coz ... you know... parsing and saving to file is much expensive then in to database.

It's not an issue btw... I just wanted to ask a question :)
If you'd like to invest some time to accomplish this... Id be glad to be involved :) 
Tho I did not yet read source good enough so maybe ill do it alone.

**Comment by Vorspire** [comment]
"parsing and saving to file is much expensive then in to database."

The database API still has to write the data to a file, so all it will do is add overhead and a dependency on a third-party application.

This isn't an issue, please use the forums for questions like these.
