### ISSUE TITLE
System.IndexOutOfRangeException: Index out of limit of array

### ISSUE THREAD

**Issue by Arutosio** [ServUO/ServUO#4546]
[Crash 11-2-2020-18-50-42.log](https://github.com/ServUO/ServUO/files/4187625/Crash.11-2-2020-18-50-42.log)
Server Crash Report
===================

ServUO Version 0.5, Build 7346.35689
Operating System: Microsoft Windows NT 6.2.9200.0
.NET Framework: 4.0.30319.42000
Time: 11/02/2020 18:50:42
Mobiles: 3
Items: 112
Exception:
System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.IndexOutOfRangeException: Indice oltre i limiti della matrice.
   in Server.Multis.HouseTeleporterTile.Initialize()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   in System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   in System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   in Server.ScriptCompiler.Invoke(String method)
   in Server.Core.Main(String[] args)

Clients:
- Count: 0

**Comment by kevin-10** [comment]
Your server is not pointed to the correct client files.

**Comment by Arutosio** [comment]
What i need to do?
