### ISSUE TITLE
crash followed by endless restart loop

### ISSUE THREAD

**Issue by Arutosio** [ServUO/ServUO#4571]
[VIDEO](https://puu.sh/Ffc9L/a0b5a66faa.mp4)
[PICTURE](https://i.imgur.com/UDp2xv5.png)
Crash Error LOG:
Server Crash Report
===================

ServUO Version 0.5, Build 7362.43151
Operating System: Microsoft Windows NT 6.2.9200.0
.NET Framework: 4.0.30319.42000
Time: 27/02/2020 23:00:46
Mobiles: 3
Items: 112
Exception:
System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.IndexOutOfRangeException: Indice oltre i limiti della matrice.
   in Server.Multis.HouseTeleporterTile.Initialize()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   in System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   in System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   in Server.ScriptCompiler.Invoke(String method)
   in Server.Core.Main(String[] args)

Clients:
- Count: 0

**Comment by kevin-10** [comment]
your using the incorrect client files for your server.

**Comment by Arutosio** [comment]
is not it compatibile with the game with client 4.0.01?
