### ISSUE TITLE
.net core?

### ISSUE THREAD

**Issue by rockytriton** [ServUO/ServUO#4600]
Sorry I looked for an appropriate forum for this on the web site but couldn't find one.  So asking here...

Is there any branch or plans to support .net core 3?  If so, do you need any help?

**Comment by TrueUO** [comment]
I would like to start considering it. We would need a ton of help.

**Comment by seanmars** [comment]
> I would like to start considering it. We would need a ton of help.

I'm really happy to hear this news. .NET Core 2 just released and I asked about it, but it didn't seem to be adopted at the time.

**Comment by Vorspire** [comment]
I think we should adopt .NET Core as soon as possible to be honest.

**Comment by TrueUO** [comment]
I'll start talking to my people too. Not sure where to start but we are down.

**Comment by rockytriton** [comment]
I'm willing to help if you need.  .net core 3.1 is pretty solid, I'm already using it in production for a couple of enterprise systems.

**Comment by TrueUO** [comment]
We talked about it today and this IS something we are going to do.

I will create a separate Discord channel and anyone who wants to help us can simply reach out to me here for an invite.

**Comment by Frostrix** [comment]
Heya, if you do end up moving this over to .NET CORE, you'll find that it doesn't support the net framework compiler that y'all are using to compile the Scripts folder into a DLL. I'd suggest using Rosyln, and I've made a mockup of how this may work here: https://gist.github.com/Frostrix/26c76751a0262fb9b4cbee8e82fc8a34

**Comment by Vorspire** [comment]
> Heya, if you do end up moving this over to .NET CORE, you'll find that it doesn't support the net framework compiler that y'all are using to compile the Scripts folder into a DLL. I'd suggest using Rosyln, and I've made a mockup of how this may work here: https://gist.github.com/Frostrix/26c76751a0262fb9b4cbee8e82fc8a34
> PS: _I was just playing around with the code so some methods are missing etc >w>, it was mainly just to show an example of Rosyln in action_

We're moving away from using Roslyn and compiling the scripts separately, to a model where the full project is compiled directly.

**Comment by Frostrix** [comment]
Ooh, right. Sounds rather interesting then.

**Comment by TrueUO** [comment]
https://www.servuo.com/threads/servuo-net-core-branch-testers-needed.12970/
