### ISSUE TITLE
Some NPCs do not handle Honesty items correctly

### ISSUE THREAD

**Issue by djredman99** [ServUO/ServUO#4686]
Creating this issue for feedback before submitting a PR for a fix.

In several cases, certain NPCs that "own" an Honesty item do not accept the item as an Honesty item.  Armourer's for instance, accept any weapon/armor item and if handed an Honesty item they are identified as an owner of, they do not grant an increase in Honesty, nor respond that the item is theirs.  Instead, they take their default behavior (in BaseVendor.cs) and say 'thanks' and some fame is awarded to the player mobile.

Another example would be the Silver Trader, they simply will not accept the Honesty item.

The reason for this is that the Honesty logic is happening in the BaseCreature class, and these certain NPCs are handling the event at either the BaseVendor or a more specific class level.  They never pass the logic to BaseCreature.cs. 

This would be easy to fix by doing a check to see if the item dropped on the NPC has a valid HonestyItemSocket at the higher class level and passing it to the BaseCreature class for the Honesty logic if it does.

**Comment by kevin-10** [comment]
Sure, push the PR and we'll go from there. Nice catch!

**Comment by djredman99** [comment]
I'll be testing a fix this evening and should have a PR soon.  Thanks!

**Comment by djredman99** [comment]
Fixed and merged in with 02f76827d00dcb2e90487f8d1dd643a662ce81de
