### ISSUE TITLE
Books are not saving correctly in the new client

### ISSUE THREAD

**Issue by djredman99** [ServUO/ServUO#4708]
The new client has changed how books are handled. Tested with client 7.0.85.15

- Book pages are now comprised of 10 lines (previously 8)
- Packets sent from the client are now 1 packet per page (previously one packet per book)

**Comment by djredman99** [comment]
How would you want to handle this @kevin-10, @TrueUO .  I would assume the best solution would be to check for which client version is connected and handle the packet accordingly?  The logic to handle the new packet should be easy enough to do.

**Comment by TrueUO** [comment]
Since we only support the newer clients, and it would be broken using older ones regardless, probably okay to just patch it for current, no?

**Comment by djredman99** [comment]
Sounds good to me. I certainly understand the desired to simplify and would be ok with it.  I’m sure that is how Broadsword operates official servers.  If you don’t patch, expect issues.  Wasn’t sure how much backwards compatibility you are trying to preserve.

**Comment by djredman99** [comment]
I should have this done next day or two.

**Comment by TrueUO** [comment]
Awesome. Yeah since this fixed a UO issue stemming from the release of the EC and how books entered there had issues displaying in the CC, and vice versa, any client that is relatively new will benefit from this. While older clients can use the current method. If you have EC questions @Argalep is the go-to guy.

**Comment by djredman99** [comment]
@TrueUO  “While older clients can use the current method”

So wait, support the older client or no?

**Comment by TrueUO** [comment]
no
