### ISSUE TITLE
Locked down item are inaccessible by Co-Owners/Friends

### ISSUE THREAD

**Issue by djredman99** [ServUO/ServUO#4710]
Items locked down in a house, such as a recall rune, a monster statue, etc. are only accessible by a Co-owner if the item was locked down by a character on the co-owners account.

If I have Co-Owner1 on AccountA who locks down a recall rune
- Co-Owner2 on AccountA will have access.  
- Co-Owner3 on AccountB will **not** have access
  + They cannot recall off of it, get an "that item is inaccessible" message

This is also true if the Owner locks down an item, them no Co-Owners will have access. This is also true of Friends of the house.

Could be related to #651 and #1316

**Comment by djredman99** [comment]
Looking for feedback if this is by design or not.  Seems odd that a locked down rune would be subjected to this behavior but i can see a case where it may be preferable for other item types.  I will eventually create an EA account to try things on their Test Center.

**Comment by kevin-10** [comment]
I always understood that items locked down are only usable or can be unlocked by either the house owner, or the player who locked them down. I know friends, are, but we would need check for co-owners. I can see where co-owners would be treated differently as friends.

**Comment by djredman99** [comment]
So I created an EJ account on official servers to do some testing and apparently you cannot place a house with an EJ account.

**Comment by kevin-10** [comment]
Rave, has this been fixed?

**Comment by djredman99** [comment]
Not sure, obviously I have been away from the game and developing here. I would keep this open for now until it has properly been compared with EA servers.
