### ISSUE TITLE
NPC vendors pay too much for e.g. exceptional player-crafted weapons

### ISSUE THREAD

**Issue by juuso** [ServUO/ServUO#4770]
It seems like at least these two lines in GenericSell.cs overvalue certain items. Looted weapons with +durability are valued in the thousands, and player-crafter exceptional weapons can be sold for ~400 gold a piece.

```
price += 100 * weapon.WeaponAttributes.DurabilityBonus;
price += 10 * weapon.Attributes.WeaponDamage;
```
Crafting exceptional weapons is pretty much a money printer with their +40% damage.

**Comment by TrueUO** [comment]
Thanks, we will take a look.

**Comment by kevin-10** [comment]
What should it be?

**Comment by juuso** [comment]
Not actually sure what the real formula is. But this bug seems to originate from the conversion from the old-style damage and durability levels.

The old levels (e.g. power, vanquishing, fortified, indestructible) were handled like this:
```
price += 100 * (int)weapon.DurabilityLevel;
price += 100 * (int)weapon.DamageLevel;
```

And then, in [this commit](https://github.com/ServUO/ServUO/commit/cc76c260fc2a8ab9f22c036b6a618221301c9804) were changed to: 
```
price += 100 * weapon.WeaponAttributes.DurabilityBonus;
price += 10 * weapon.Attributes.WeaponDamage;
```

The DurabilityLevel used to range from 0-5. Now each percentage point is accidentally handled like an old level, giving huge price increases. For example, a meager +5% durability bonus is priced like an indestructible weapon. The damage is handled somewhat more sanely.
