### ISSUE TITLE
Error running on macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by lucasrencoret** [ServUO/ServUO#4778]
runned `brew install mono`, then `make` and I receive this error:
`error CS1644: Feature 'default literal' cannot be used because it is not part of the C# 7.0 language specification`

Is this code working for Mac?

**Comment by kamronbatman** [comment]
I personally never got it working on OSX.

**Comment by Fire-Dragon-DoL** [comment]
The same problem is happening on Ubuntu, this could be problematic because it makes sense to host an Ultima online server on an Ubuntu machine.

The problem is that mono has partial support for C# 7, but it doesn't mention 7.1.
The `default` keyword is part of 7.1.

**Comment by kamronbatman** [comment]
Mono doesn't work well on Linux so I don't recommend it at all. You should convert ServUO to .net core and then you will have C# 8 support. Or wait until November/December for .Net 5

**Comment by Fire-Dragon-DoL** [comment]
I'm happy to switch to.NET core, but the instructions mentioned mono, that's why I used it. Once I figure out how to compile it, I'll make a PR for the readme.
I'm not sure if the Makefile needs to be updated.

**Comment by kamronbatman** [comment]
It is not about just compiling it, there will be _some_ code changes. I know the ServUO team would be happy to see a PR for .net core.

**Comment by TrueUO** [comment]
Oh, absolutely...

Currently, with just myself, Dexter, and Argalep, we really don't have the know-how on how to do this correctly and efficiently while maintaining support for the shards currently using ServUO code.
