### ISSUE TITLE
Cleanup Trash Barrel

### ISSUE THREAD

**Issue by Tauriella** [ServUO/ServUO#4799]
Why do they remove the clean up trash barrel?

![OSI](https://user-images.githubusercontent.com/10637389/85413281-e583c380-b56a-11ea-97c0-92857b6cfb18.png)
Which are also available at OSI

**Comment by TrueUO** [comment]
Just say [add trashchest

There were TWO items that did the same thing in the core. The old didn't even have check for the cavern of discard chance.

That one is wrong so it was removed. You still have the trash chest.

**Comment by Tauriella** [comment]
Ahh 
ok
thank you :+1:
