### ISSUE TITLE
Mysterious Fragment ( Server Crash )

### ISSUE THREAD

**Issue by Tauriella** [ServUO/ServUO#4811]
If Player drop a Mysterious Fragment on the ground  non Shrine Area the Server will crashed.

**Comment by TrueUO** [comment]
Thanks, taking a look.

**Comment by TrueUO** [comment]
Got a copy of the crash log you can upload?

**Comment by Tauriella** [comment]
`Server Crash Report
===================

ServUO Version 0.5, Build 7494.1618
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Framework: 4.0.30319.42000
Time: 07.07.2020 22:55:23
Mobiles: 77544
Items: 441062
Exception:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Server.Items.MysteriousFragment.DropToWorld(Mobile from, Point3D p) in D:\ServUOSRC\ServUOSRC\Scripts\Services\Seasonal Events\JollyRoger\Items\MysteriousFragment.cs:Zeile 51.
   bei Server.Mobile.Drop(Point3D loc) in D:\ServUOSRC\ServUOSRC\Server\Mobile.cs:Zeile 4713.
   bei Server.Mobiles.PlayerMobile.Drop(Point3D loc) in D:\ServUOSRC\ServUOSRC\Scripts\Mobiles\PlayerMobile.cs:Zeile 2586.
   bei Server.Network.PacketHandlers.DropReq(NetState state, PacketReader pvSrc) in D:\ServUOSRC\ServUOSRC\Server\Network\PacketHandlers.cs:Zeile 1141.
   bei Server.Network.MessagePump.HandleReceive(NetState ns) in D:\ServUOSRC\ServUOSRC\Server\Network\MessagePump.cs:Zeile 341.
   bei Server.Network.MessagePump.Slice() in D:\ServUOSRC\ServUOSRC\Server\Network\MessagePump.cs:Zeile 135.
   bei Server.Core.Main(String[] args) in D:\ServUOSRC\ServUOSRC\Server\Main.cs:Zeile 645.
`

**Comment by TrueUO** [comment]
Thanks @Argalep has a fix. I am pushing it over here in a few minutes. Stay tuned! :)

**Comment by TrueUO** [comment]
Alright, fix is in just waiting on the standard review.

**Comment by Tauriella** [comment]
Thanks works perfekt :+1:
