### ISSUE TITLE
XML Spawner Bug 

### ISSUE THREAD

**Issue by Tauriella** [ServUO/ServUO#4910]
XML Spawner Bug 
You cannot save attributes in the spawner's book

![XMLBug](https://user-images.githubusercontent.com/10637389/101315148-4aea1900-385a-11eb-9a77-0432cb48d90e.jpg)

**Comment by Goobe7** [comment]
![屏幕快照 2020-12-14 00 36 35](https://user-images.githubusercontent.com/18004275/102016610-15d34e80-3da5-11eb-878b-d72a5d2c3442.png)

**Comment by Tauriella** [comment]
Enter your values ​​in the book and you will see that it is not saved

**Comment by kevin-10** [comment]
This could be due to book packet changes, or many of the neat XML spawner functions being removed.

**Comment by Tauriella** [comment]
Hi
Why you close this issue if the Bug present is?
