### ISSUE TITLE
Topics to About section

### ISSUE THREAD

**Issue by Nerun** [ServUO/ServUO#4915]
Would be good to add the **topics** bellow to the section **About** of GitHub.

- gpl
- gplv2

gpl and gplv2 are for licenses of course

**Comment by Vorspire** [comment]
GitHub already facilitates links to the relevant license for the project in the About section.
![image](https://user-images.githubusercontent.com/295475/104235815-6ba32100-544d-11eb-9ad7-4cdf1805851e.png)

**Comment by Vorspire** [comment]
I've added your suggestions to the tag-cloud (Topics)
