### ISSUE TITLE
EASY FIX for "TimeZone" warnings

### ISSUE THREAD

**Issue by Nerun** [ServUO/ServUO#4921]
This is a fix for this warnings:

![warnings](https://user-images.githubusercontent.com/3987342/106387289-df36af00-63b7-11eb-8c99-dd63aad149bc.png)

They are deprecated warnings for TimeZone class. It happens in Publish 57 in this files:
* /Scripts/Services/Reports/Rendering/HtmlRenderer.cs
* /Scripts/Services/Town Cryer/Gumps/CreateGuildEntryGump.cs
* /Scripts/Services/Town Cryer/Gumps/TownCryerGuildGump.cs

I know that in the current master branch (Jan 18, 2021) there is no "Reports" folder, and i can't find HtmlRenderer.cs anymore, but for Town Cryer gumps, both are still there, and the warnings was not fixed yet.

Here an easy fix for you guys: [Scripts.zip](https://github.com/ServUO/ServUO/files/5899924/Scripts.zip)

**Comment by Vorspire** [comment]
:)
