### ISSUE TITLE
Pet disappearing from stables 

### ISSUE THREAD

**Issue by Mr-Kirkman** [ServUO/ServUO#4930]
This has happened a few times now.

When a bonded animal goes wild, and you retame it.  

Feed it and stable it.  

It then is removed from your stables and lost forever.

**Comment by TrueUO** [comment]
![Horse](https://user-images.githubusercontent.com/20760229/114795539-ca35af00-9d5c-11eb-8fee-ffcd292ba263.png)
I bonded a horse, forced it to go wild, retamed it, feed, and stabled it.

It did not delete.

I restarted the test shard. It did not delete.

Is it instant?
