### ISSUE TITLE
Enter the Ultima Online directory

### ISSUE THREAD

**Issue by thiagoedson** [ServUO/ServUO#4936]
Sorry I may not have understood the project, I am following a wiki, but it does not address this step, and even informing some directory over there it is getting in a loop with the following error

Server Crash Report
===================

ServUO Version 0.5, Build 7809.14024
Operating System: Microsoft Windows NT 6.2.9200.0
.NET Framework: 4.0.30319.42000
Time: 19/05/2021 10:51:18
Mobiles: 1
Items: 1
Exception:
System.Reflection.TargetInvocationException: Uma exceção foi acionada pelo destino de uma chamada. ---> System.TypeInitializationException: O inicializador de tipo de 'Server.TileData' acionou uma exceção. ---> System.Exception: TileData:  not found
   em Server.TileData..cctor()
   --- Fim do rastreamento de pilha de exceções internas ---
   em Server.TileData.get_ItemTable()
   em Server.Item.get_ItemData()
   em Server.Item.UpdateLight()
   em Server.Items.BaseArmor..ctor(Int32 itemID)
   em Server.Mobiles.SeaMarketOfficer.InitBody()
   em Server.Mobiles.BaseVendor..ctor(String title)
   em Server.Engines.Quests.MondainQuester..ctor()
   em Server.Mobiles.SeaMarketOfficer..ctor()
   em Server.Mobiles.SeaMarketOfficer.Initialize()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   em System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   em System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em Server.ScriptCompiler.Invoke(String method)
   em Server.Core.Main(String[] args)

Clients:
- Count: 0

**Comment by Vorspire** [comment]
You need to change the path to your copy/installation of UO in Config/DataPath.cfg
When you change the value of the DataPath setting, make sure to remove the @ if one prefixes the value.
