### ISSUE TITLE
Mobile status isn't sent at certain ranges due to player's update range being ignored

### ISSUE THREAD

**Issue by roxya** [ServUO/ServUO#4947]
When the client opens the healthbar of a mobile, an 0x34 MobileQuery packet is sent. If the mobile is within update range, ServUO will reply with 0x11 MobileStatus.

It appears however that ServUO uses the update range of the mobile being queried, rather than the player making the request. In the case of NPCs, and players who have a smaller update range than the requesting player, this can mean a failed Utility.InUpdateRange check, even though the mobile is visible on screen. The result is a blank healthbar - no name, no health.
![image](https://user-images.githubusercontent.com/7057924/124397412-90df6080-dd07-11eb-8730-401c42937245.png)

**Reproducing in Classic Client 7.0.90.16**

- Set your screen size to one of the larger sizes (I believe the bottom 3 resolutions in the options), which increases your update range to 24 tiles.
- Stand further than 18 tiles from an NPC, but still within visible range.
- Pull the healthbar. It will be blank
- Move within 18 tiles, and re-open it. It will now have the name and health

**Reproducing in ClassicUO**
- Will by default request 24 tiles update range, so there's no special action to take
- Stand further than 18 tiles from an NPC, but still within visible range.
- Pull the healthbar. It will be blank
- Move within 18 tiles, and re-open it. It will now have the name and health

**Comment by Vorspire** [comment]
This is very likely already resolved in the P58 branch, which is almost ready to merge to master.
