### ISSUE TITLE
Kashiel's quest can't be completed

### ISSUE THREAD

**Issue by Agetian** [ServUO/ServUO#4957]
Kashiel's quest (as defined in Kashiel.cs) to slay 10 sheep ("I Shoot An Arrow into the Air") currently can't be completed because the Completed entry isn't defined. This results in an empty quest window appearing with no buttons, which can't be closed (you have to e.g. talk to another quest giver and click the close button there to close both windows at once).

The quest definition file is missing this entry:

`        public override object Complete => 1075485;`

If this line is added, the quest can be finished normally and the reward is given.

**Comment by Tauriella** [comment]
Hi
I have tested this Quest with the latest release and it works without problems.
Use you the latest release ?

**Comment by Agetian** [comment]
Hi Tauriella, thank you for looking into it!
I tested it with the current upstream master (cloned git) as of August 10.
I checked the definition of the quest in the current version (as of August 23) and it still lacks the Completed entry, later today I'll try to clone the latest git and re-test the quest itself to see if anything has changed.

**Comment by Agetian** [comment]
I re-tested in the current git (Aug 23) and I can confirm that it's no longer an issue, must have either been fixed already by something or maybe was something on my end due to the way I updated. At any rate, closing.
