### ISSUE TITLE
Client Crash with no error logs or messages, caused by itemID 201 & 202

### ISSUE THREAD

**Issue by tass23** [ServUO/ServUO#4962]
On Discord recently, I mentioned that I kept getting DC'd in Serpent's Hold and Sidle said the same thing. Apparently this is a bug with certain clients (maybe all clients...?) and Serpent's Hold (Fel & Tram).

I discovered an issue with two itemIDs that were part of a custom addon build that was placed, frozen and causing everyone to disconnect when they got too close. Clients will just crash with no warning and no error messages. After replacing them with itemIDs 234 and 240, no more disconnects.

itemIDs in question:
201 - 0x00C9
202 - 0x00CB

One is a regular stone wall and the other is an arrow loop.
Spot in Serpent's Hold is as you get closer to the keep, near where the ground is burned from a fire pit it looks like.
Using Xmlfind, I did not locate those itemIDs anywhere else on my 'shard, so they might already be frozen.

Update: Xuri on Discord was able to demonstrate that this might be specific to ServUO, as they were able to drop three of these items near them without crashing.

EDIT: Estonia said Pub 57 does not have this issue. It seems that is also when ServUO started coding for UOP files. That might be the change that fixed clients for that pub.

**Comment by Vorspire** [comment]
99.9% certain it's not a server-side issue. Has anyone other than yourself been able to reproduce it?

**Comment by tass23** [comment]
Sidle mentioned having this problem as well, on Discord when I brought it up.

**Comment by DocKnight86** [comment]
Where in Serpents Hold are these itemIDs? I'd like to run around by them and see what happens.

**Comment by Vorspire** [comment]
Does adding dynamic items using these ID's cause the issue?
[add static 201

If the issue only happens in Serp's Hold, then it's more likely something to do with the map or statics in that area.

**Comment by tass23** [comment]
Well Sidle said they removed a portion of that map with Dragon and it did not fix the issue.

Yes, when I tried to add it with the ADD command, crash.
Spawning it and getting too close is a crash.
Having it part of an addon made with AddonGen, crash.

I did find another clue and this may mean it is not server-side at all, in which case I do not know if this needs to be here anymore, but:
Some people reported itemIDs being shifted converting from UOP to MUL and back again.
If that is the case, the server is reading the info correctly, but the data shifted by one slot.

I do not know if Sidle converted though.

**Comment by Vorspire** [comment]
Interesting, but surely it'd break everything, not just these two tiles.
I'll also look into it soon to see if I can reproduce and debug it.

**Comment by TrueUO** [comment]
![show](https://user-images.githubusercontent.com/20760229/132954106-4701c7dd-ef99-40ec-a90d-64d334ba7300.png)
I can't replicate it.

Though I did notice 0x00C9 and 0x00CB, when added using [add static 0x00C9 is simply 0xC9. However, regardless, I can run around them just fine using the newest client.

**Comment by TrueUO** [comment]
Static 202 is 0xCA and no issue where either.

**Comment by tass23** [comment]
True, which Pub are you using? Is it prior to Pub 57?
That seems to be the turning point.

After thinking about that Fiddler shift, it does not make sense either.
Like Vors said, it would screw up everything else, so that tells me something specific changed for these two items.
Could be they added new graphics or anims at that point and/or changed some flags.

What about Fiddler info?
Here are screenshots of my client's 200 - 203. So the Stone Wall in front of the one I have trouble with and the arrow loop behind the one I have trouble with:
![200_203_Fiddler_1](https://user-images.githubusercontent.com/23402105/132976780-a06b368c-8447-40b9-8ab7-ff9970eb0667.jpg)

The Stone Walls are the same, but the arrow loops are not. I have no idea, but Quality is not going to cause this, right?
