### ISSUE TITLE
StaffRuneBook gone...what else is there?

### ISSUE THREAD

**Issue by tass23** [ServUO/ServUO#4964]
StaffRuneBook was part of Nerun's forever and it was the best way to get around any 'shard as it generated the Runebooks from the location files.

Can that get put back? Or did it get replaced with some other command?

**Comment by Vorspire** [comment]
It's a custom modification from a third-party author who isn't updating or supporting it actively.
ServUO has removed systems like this, or stripped them down to basics (as is the case with XmlSpawner), as they are not critical to the project or the ability to start up a shard.
It won't be included in the distribution for the foreseeable future.

**Comment by tass23** [comment]
Then how do staff navigate around the 'shard?
The StaffRunebook itself was a simple system. You do not need to add the whole toolbar as well.

Guarantee you that Broadsword has a way for staff members to travel the 'shard.

**Comment by Vorspire** [comment]
Perhaps try one of the other hundred ways to move around the world, like [go, [self set location, walking... or even a normal rune book.

Don't ask these questions if you're not satisfied with the answer.
