### ISSUE TITLE
Dragon Armor

### ISSUE THREAD

**Issue by KrystalGold** [ServUO/ServUO#5000]
Yellow scales in Resource Info has poison resist twice rather than energy resist which should be 1.
![DARGON ARMOR](https://user-images.githubusercontent.com/87610617/160589088-fa5685e0-8e1e-4c8c-ba4b-f23983984310.jpg)

**Comment by okk3** [comment]
Heyo @KrystalGold,

thanks for the info, I sent a PR with the fix, hopefully they can push it soon :)

Best Wishes
