### ISSUE TITLE
Freezes on Linux

### ISSUE THREAD

**Issue by Clooloo** [ServUO/ServUO#5011]
Hello all, I have tried to get this to run on several Linux distributions with several version on Mono, zlib1g, and dotnet, and no matter what I try servuo freezes with no error no crash  no nothing, Host still lives and process can easily be stopped but nada always same results freezes after 1 or 2 Minutes.

I have Tried Debian 9,10,11 and Ubuntu 18.04, 20.04, 21.10 and 22.04, All clean installs and nothing but ServUO and requirements on server, I used to run on Linux and it was perfect.
I have tried dontnet 5.0 and 6.0 with same results
I tried Mono 6.12(On Latests Ubuntu), 4.6 (on Debian 9), 5.18(On Debian 10), 6.8(On Debian 11)
I tried zlib1g 1.2.8 on Debian 9, 1.2.11 on Debian 10 and 11 

All the same resualts, Everything works perfect, I start and save the server but Servuo Alone freezes only ServUO and nothing else :( anything will be done or I shall forget about using Linux? please help. are there specific versions that I need to get?

**Comment by kaczy93** [comment]
Did you try waiting few minutes? There are some tasks like auto generation and cleanup that run few minutes after start up that can freeze whole server for even 10 minutes. You can also run your server with a debugger, interrupt the proces and see what the main thread is working on.

**Comment by Clooloo** [comment]
I have not let me try this not, also someone suggested running it with dotnet and not with Mono let me try this as well, I will get back.

**Comment by Clooloo** [comment]
Dont worry Im just gona have to go with Windows.

**Comment by Clooloo** [comment]
I switched to Windows, and it is still freezing :( clean windows server, the latest client can client be the problem?

**Comment by Clooloo** [comment]
Release 57.1 does not freeze only latest nightly

**Comment by kamronbatman** [comment]
ServUO was never battle tested on Linux. Not recommended to use it, especially considering the myriad of problems with Mono.
