### ISSUE TITLE
dotnet 5 is EOL about 6 months ago

### ISSUE THREAD

**Issue by roracle** [ServUO/ServUO#5031]
I found this out while trying to set up a private server at home and I'm running Fedora 37, which has removed dotnet 5 from the repos because it's no longer supported. All I have access to is version 6.  I'm getting the following error:

`Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/home/roracle/Downloads/ServUO-57.2/Scripts/Scripts.csproj : warning NU1503: Skipping restore for project '/home/roracle/Downloads/ServUO-57.2/Scripts/Scripts.csproj'. The project file may be invalid or missing targets required for restore. [/home/roracle/Downloads/ServUO-57.2/ServUO.sln]
  Determining projects to restore...
  Nothing to do. None of the projects specified contain packages to restore.
/usr/lib64/dotnet/sdk/6.0.110/Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.8 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/roracle/Downloads/ServUO-57.2/Server/Server.csproj]

Build FAILED.

/home/roracle/Downloads/ServUO-57.2/Scripts/Scripts.csproj : warning NU1503: Skipping restore for project '/home/roracle/Downloads/ServUO-57.2/Scripts/Scripts.csproj'. The project file may be invalid or missing targets required for restore. [/home/roracle/Downloads/ServUO-57.2/ServUO.sln]
/usr/lib64/dotnet/sdk/6.0.110/Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.8 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/roracle/Downloads/ServUO-57.2/Server/Server.csproj]
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.33`

**Comment by pyro17** [comment]
".NETFramework,Version=v4.8 were not found."

I dont think you have mono installed, Net wouldnt drop target versions, since that would break a lot of programs and would give a big backlash.

**Comment by bohica89** [comment]
Did you try running a windows emulator inside linux to see if you still get the same error?

**Comment by pyro17** [comment]
This is not a linux issue. He is missing net framework, and for linux that is mono
