### ISSUE TITLE
DyeTub has an easy crash-fix

### ISSUE THREAD

**Issue by Ultima-Lokai** [ServUO/ServUO#5056]
In DyeTub.cs around line 163, change this:

`

                                    BaseHouse house = BaseHouse.FindHouseAt(item);

                                    if (!house.IsCoOwner(from))
                                        from.SendLocalizedMessage(501023); // You must be the owner to use this item.
                                    else if (house == null || (!house.IsLockedDown(item) && !house.IsSecure(item)) && (!(item is AddonComponent) || !house.Addons.ContainsKey(((AddonComponent)item).Addon)))
                                        from.SendLocalizedMessage(501022); // Furniture must be locked down to paint it.
                                    else
                                        okay = true;
`

To this:

`

                                    BaseHouse house = BaseHouse.FindHouseAt(item);
									
                                    if (house != null)
									{
										if (!house.IsCoOwner(from))
											from.SendLocalizedMessage(501023); // You must be the owner to use this item.
										else if (house == null || (!house.IsLockedDown(item) && !house.IsSecure(item)) && (!(item is AddonComponent) || !house.Addons.ContainsKey(((AddonComponent)item).Addon)))
											from.SendLocalizedMessage(501022); // Furniture must be locked down to paint it.
										else
											okay = true;
									}
									else
										from.SendMessage("Furniture must be locked down in your house to paint.");`

**Comment by Voxpire** [comment]
Can you submit this in the form of a Pull Request please?
