### ISSUE TITLE
[CRAFT] BS BoD generation Issues

### ISSUE THREAD

**Issue by NickEU** [ServUO/ServUO#580]
[Current chance to get LBoDs](https://github.com/ServUO/ServUO/blob/8c88179cb1f0a0fcea1032f87bba0ea51b943126/Scripts/Mobiles/Vendors/NPC/Blacksmith.cs#L116)
This can't be right, you basically get punished the bigger your real BS skill is = 26% of your bods at 120 skill will be large ones, when in reality you should get like 8% of your BoDs as LBoDs...
[Forum post with some thourough testing of BoD generation system on OSI](http://stratics.com/threads/bod-drop-changed.245896/#post-1982438)
Also , the same goes for colored armor bod chances in that same post. 
Looks like the code for BoD generation hasn't been touched in over 10 years, which is not good, here's an old thread from easyuo forums about runuo that sports the same BoD code : 
[Looks familiar? :P](http://www.easyuo.com/forum/viewtopic.php?t=26972)
There need to be some changes, it's bad enough that the new magic item generation system made runics totally worthless. I understand that bribery is the most recent BoD addition and something you should end up with in the end, but for now you can at least do some adjustments that happened in between the bribery and the old system.
[Official Publish 50 notes](http://www.uoguide.com/index.php?title=Publish_50&mobileaction=toggle_view_mobile)

> Increased chance for GM smiths to get a hued BOD: +20% at 110 skill, +40% at 120 skill
> Increased chance of receiving a Valorite BOD

The first one basically confirms the numbers from the forum post i linked earlier so there's no reason to think the LBoD chance part is not credible as well.

If i understand this right here's the outdated code used for BoD material chance: 
[LBoDs](https://github.com/ServUO/ServUO/blob/0100311687f80658e5e3e7a69ddef38c717c63a8/Scripts/Services/BulkOrders/LargeSmithBOD.cs#L9)
[SBoDs](https://github.com/ServUO/ServUO/blob/0100311687f80658e5e3e7a69ddef38c717c63a8/Scripts/Services/BulkOrders/SmallSmithBOD.cs#L10)

**Comment by qbradq** [comment]
Thanks Nick! VERY thorough.
