### ISSUE TITLE
Three errors preventing server launch.

### ISSUE THREAD

**Issue by HankTheDrunk** [ServUO/ServUO#703]
I just tried to launch the server as it stands and I receive the following errors.

 Errors:
  + Mobiles/Normal/OrcChopper.cs:
     CS0246: Line 132: The type or namespace name 'StoutWhip' could not be found (are you missing a using directive or an assembly reference?)
  + Quests/HonestBeggar.cs:
     CS0246: Line 11: The type or namespace name 'Regina' could not be found (are you missing a using directive or an assembly reference?)
     CS0246: Line 102: The type or namespace name 'Evan' could not be found (are you missing a using directive or an assembly reference?)
  + Quests/UnfadingMemories.cs:
     CS0246: Line 100: The type or namespace name 'Thalia' could not be found (are you missing a using directive or an assembly reference?)
     CS0246: Line 193: The type or namespace name 'Emilio' could not be found (are you missing a using directive or an assembly reference?)

**Comment by qbradq** [comment]
Thanks Hank! I think a few files got left behind in the move. I'll hunt them down.

**Comment by qbradq** [comment]
Huh, these few files just got straight lost. I've re-added them from a previous commit. Should be resolved now. At least it builds in Visual Studio.
