### ISSUE TITLE
[ADMIN] " See the file : <runuo root>/objects.log "

### ISSUE THREAD

**Issue by zerodowned** [ServUO/ServUO#726]
https://github.com/ServUO/ServUO/blob/54e5c469eae56cf952b18c70a713c1237b4ea1bc/Scripts/Commands/Profiling.cs#L143

When using the command CountObjects it generates a file and displays the message " See the file : <runuo root>/objects.log "

**Comment by qbradq** [comment]
What's wrong with this message?

**Comment by zerodowned** [comment]
It's tell the user to look in the RunUo root folder, not the ServUo root folder
