### ISSUE TITLE
Weapon Elemental Damage

### ISSUE THREAD

**Issue by ShadwDrgn** [ServUO/ServUO#872]
On official shards since AOS weapon drops on mobs have a chance of dropping with mixed elemental damage. This is often how players would get 100% poison or cold damage weapons for melee training. This does not appear possible or at least so rare i've never seen it happen in ServUO shards.

**Comment by ShadwDrgn** [comment]
I've submit a pull request as a suggested fix for this:
https://github.com/ServUO/ServUO/pull/874

**Comment by antolmkk** [comment]
The fact is on OSI there is a chance to drop weapons with mixed elemental damage, chaos damage or 100% elemental damage, but The chance is small. There is a better way for obtain 100% elemental damage weapons, re-forging, and enhancing. You can enhance into 100% elemental weapon whatever weapon with mixed damage 70 elemental/30 physical.

**Comment by ShadwDrgn** [comment]
Whether there is another way or not and whether your opinion is that it's better is irrelevant. We're not making a new game here. As for the chance being small, I've been killing Miasmas on official to test this, and I seem to get a weapon with mixed elemental damage every 1-2 Miasmas. Additionally if we assume you get about 5 properties per item using the old drop system and a 1 in 27 chance to get elemental damage per property you chance is roughly 1 in 5.4 to get a weapon with mixed elemental damage using that system. Additionally this isn't about getting 100% elemental damage weapons. It's about getting elemental damage weapons at all. I'm using the same function that the old drop system used to assign the elemental damages, so the chance of a 100% weapon is still just as low.

**Comment by antolmkk** [comment]
Old drop system. True. You are not doing a new game here.

**Comment by ShadwDrgn** [comment]
We're not using the old drop system. I meant the old drop system in ServUO. I'm testing the same drop system on OSI that we're using now.

**Comment by ShadwDrgn** [comment]
To be 100% clear. The Drop system currently in use in ServUO is the same as on OSI's current official shards. That system should be giving mixed elemental weapon damages sometimes on weapon drops. This has ALWAYS been the case on OSI whether in the new or old systems. I used the old system to make a comparison to determine chances of a drop. If someone feels this isn't OSI accurate, please say so and make a suggestion. PooPooing the issue because "there's a better way" isn't helpful. Thanks.
